# Generated by Django 4.0.3 on 2022-06-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bizinfo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('ministry', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=2000)),
                ('link1', models.CharField(max_length=200)),
                ('link2', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
