# Generated by Django 4.0.3 on 2022-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOHelp', '0002_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizinfo',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bizinfo',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bizinfo',
            name='ministry',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bizinfo',
            name='period',
            field=models.CharField(max_length=200),
        ),
    ]
