# Generated by Django 4.0.3 on 2022-06-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOHelp', '0003_alter_bizinfo_id_alter_bizinfo_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizinfo',
            name='link1',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='bizinfo',
            name='link2',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
